baseurl = "http://www.example.com"
title = "Joseph Levarato"

theme = "coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Welcome to my website"
    description = "Joseph Levarato website"
    keywords = "blog,developer,personal"
    info = "Unfortunately, there's nothing here yet."

    hideCredits = false
    hideCopyright = false